language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: NnicPQlHJh4uzBJ6H92XX/JZKW9XxKpE0Q4L1rGIrFjE6NtpeXH5g9gKZgynlh45oQEgArdbH4/uCKxBTvqEujlSGy5bcXUkZ4LfukNqiqL8tSfWaIIkyWNYQMXfsqyg7XhZZsMFnoBoALLgyd709vTKtzRX33QN8xfBvAkyUNnq8m+r36n+wKg+iDiDXpFxGaOB6bXkhMPr51wp56RREOu/1ZidRRV4LWoPtMsxAJVLnkZgZCovx4sinSpvvZX6BIMF9On7tsd4XREPRPNyfyr2upw1p1un8QZO50oLWLxFBnHHSJat0aStBvwK6rAdGkI6IcBGGFKOmKUUBYEjA6zMD/RL1REhbFsPAECfkcfmtVMg+TdAIVP4otzruVvqDXsDj6LCuZvFEjeW3tPHTZVqlrZOUVpYfQe95qBJPELoanpYn+LID7d3UXOo5vFWKYYEXNfh72RkG4aIJrgYHhffvKtpeGN/zq5Ga/Jjy/+Gl5Rg963tFMJnCziBQR06IPrvi+RWWPUS+2q8antwTuKplqKy/enm8KzxgTYhyqfF0odyacptD1GZCSnuhnKewV650H9l7bvbQ+Jl1D08L3lUUlgsZcdBbrAE81gJcA1BwaJWYi90cw3W7jG9sJjpwUvPDMtZGXVr22ICAIze/2Dl6Z97LJwQ8/qOgyeUAqI=
  app: react-weather-temp-app
