language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: l1cd6ao5QTg89cfyxJVMqfWVmjnKfSSGlEvgDdAC7sJ6B44mU51wWc+NP/yaYEkwIaOvevr1QZ7mlHE9OhnkuS4fS+EKZxt+CLpAAqa9XHVmoODBm/XeJlGEPdktWN71/LOP11EHLXuwCts52xsfCVIYp5WtbuvERxUE1cs/7uVBJpLdut03pHrXSJRH8Bzdo7kVq0a8fem8NdH7b7VQ1U15BxcLSZ6Zi9wDwlPQTjAnMKyIloMBmwQB/yJ6Yy2LrkIhj6kCK2+WjdEmVUxDI7EG2Vb9DCenj+wZXBiO5bv5kZY00lSBF3Oxgb+penJOAexYpafAn47r6YQTFntdAsVLUDFbqxLM3TqXB+b4DDXBNYllriIraO6Z/FksL1cj+xKQJC93nFi47bGVCF6+yh3Imyd9WIrtKj83ktd00bg5jCTyAyCd0lau7wnpuNa07M3mzo2JoRvT8eY7jHyxbTjkq7dyjzjxC9Q8DZMaSb53f3hBCcQ0ZnRihfZVEqhr/upuXpWfe45sWEbuyDnPlxSXIEfq1Ws+4eL2g9b3cKRJgmx4hst4/EsAf5bj4afgx341QgFlmJuwXSGaH6LP9NfBB+pC/NShfc4VJED7nbkEoFHMtaA7B+eDBTvsFXaur6vWzJnTGBuz24LMwH0ZwlPbCX9EbZqrYfQJPkq8tOA=
  app: react-weather-temp-app
