language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: EzC62yU7djeLUvT/RuheXuQ8CBiONjIZC8zonj+kHUr/wo21oUic4kxHxpP4Zk2/Eif5Jgf1FkdD7rRRB3LB4PTyJjpXF/X5sRw7AzP5ew6Y7Mh59z+tefKmnJ2/fWVluU7fzge7FGk4cQyy6VzwZum9B5k3HKWWIXvsd4piQkY4KVRNj55tya8LxwUh+MS/81WAMb4KRwtPN4EmgkEET40lgVkwzpihNo1G+hFXGVSSCD9wer2bdCLFNvXvfCFG4NFvwckNfQeaESfPf/B7x4acQLvePL8un6Wbs2QhNLSxgd2PPnSy+jeSIm7Xi3i4vvoFw4Y5GIsLYJ58+7D0sdKnWz7tMqGGE19GCehuB/jOfKB0rH/uIB2MR2+g2PtAnGRirBcO5g6SkEw9MwkexvvSkCGHatmNCKWdbqHx0bS7AcbEjWD9SQoVJQszBpkcP96FbDRnFVl69JRjKGqoNfeyLLGHxWryudidiAb0+efCzfYyfklZtqtsGwt9bqOH6OdC4ghHtllEdFeTig0h0vJNVqUi6PT+UH1Qh+G5MDNpPmk1E6ITlEPSppWzmfMRFvEp8Lli7j66aaFDT1aLc14HW5vQMvFBmI4C/dlLBBtbyNb1cQ2d8Eb1jp+3BoYh1BBfkg5iP11MWzrJ448jNd39oWGO7Pfrmlb2ohvpy2k=
  app: react-weather-temp-app
